base_model: /home/jhqy/IRF/finetuning/qwen3/Qwen3-4B
trust_remote_code: true
strict: false
force_no_bitsandbytes: true


chat_template: qwen3

datasets:
  - path: /home/jhqy/IRF/finetuning/qwen3/data/db_train.json
    type: chat_template
    split: train
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

val_set_size: 0.2
output_dir: /home/jhqy/IRF/finetuning/qwen3/outputs/qwen3-4b-lora-db
dataset_prepared_path: last_run_prepared

# ==== 性能关键参数 ====
sequence_len: 1024        # 你是 16GB，2048 太大；1536 性能最优
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

# ==== 自动续训 ====
# resume_from_checkpoint: latest

# ==== LoRA ====
adapter: lora
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - down_proj
  - up_proj

# ==== 批大小（16GB 的最佳设置）====
micro_batch_size: 2
gradient_accumulation_steps: 2
# -> 等效 batch size = 4，不会爆显存

# ==== Epoch（你的28000条数据）====
num_epochs: 4

# ==== 学习率 ====
learning_rate: 5e-5
warmup_ratio: 0.1
lr_scheduler: cosine

# ==== 正则与稳定 ====
weight_decay: 0.01
max_grad_norm: 1.0

# ==== 精度 ====
bf16: true
fp16: false
tf32: true

# ==== 显存优化 ====
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# ==== 注意力优化 ====
flash_attention: false        # Blackwell 不兼容
flex_attention: false          

# ==== 日志 ====
logging_steps: 5
evals_per_epoch: 2
saves_per_epoch: 1
wandb_project: qwen3_ift
wandb_run_name: qwen3_4b_lora_db
